### ISSUE TITLE
Plugin scaffold does not compile

### ISSUE THREAD

**Issue by henhal** [dtsgenerator/create#6]
Hi,
So I decided to try to create a plugin to see if I could have it create some extra types for me.

However, the boilerplate created by `npm init @dtsgenerator create-operation-map` fails both to compile and test.
I don't know if this could be to some version mismatching (ts 3.9.7 is installed globally on my system), in which case perhaps `npx` or something is needed - or if this is in fact broken?

```
$ npm run build

> dtsgenerator-create-operation-map@0.1.0 build /home/henke/github/dtsgenerator-create-operation-map
> npm run compile


> dtsgenerator-create-operation-map@0.1.0 precompile /home/henke/github/dtsgenerator-create-operation-map
> npm run lint


> dtsgenerator-create-operation-map@0.1.0 lint /home/henke/github/dtsgenerator-create-operation-map
> eslint *.ts **/*.ts


/home/henke/github/dtsgenerator-create-operation-map/test/snapshot_test.ts
   12:2   error  Replace `·` with `;`  prettier/prettier
  139:20  error  Insert `·`            prettier/prettier
  140:1   error  Insert `·`            prettier/prettier

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.
```

And

```
$ npm test

> dtsgenerator-create-operation-map@0.1.0 test /home/henke/github/dtsgenerator-create-operation-map
> nyc npm run do-test


> dtsgenerator-create-operation-map@0.1.0 do-test /home/henke/github/dtsgenerator-create-operation-map
> cross-env TS_NODE_FILES=true mocha --exit --require ts-node/register --colors test/*_test.ts


TSError: ⨯ Unable to compile TypeScript:
test/snapshot_test.ts:124:53 - error TS2322: Type 'TransformerFactory<SourceFile>' is not assignable to type 'TransformerFactory<Node>'.
  Types of parameters 'context' and 'context' are incompatible.
    Type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").TransformationContext' is not assignable to type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").TransformationContext'.
      The types returned by 'getCompilerOptions()' are incompatible between these types.
        Type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").CompilerOptions' is not assignable to type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").CompilerOptions'.
          Index signatures are incompatible.
            Type 'string | number | boolean | string[] | (string | number)[] | import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").MapLike<string[]> | ... 4 more ... | undefined' is not assignable to type 'string | number | boolean | string[] | (string | number)[] | import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").MapLike<string[]> | ... 4 more ... | undefined'.
              Type 'TsConfigSourceFile' is not assignable to type 'string | number | boolean | string[] | (string | number)[] | MapLike<string[]> | PluginImport[] | ProjectReference[] | TsConfigSourceFile | null | undefined'.
                Type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").TsConfigSourceFile' is not assignable to type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").TsConfigSourceFile'.
                  The types of 'statements.concat' are incompatible between these types.
                    Type '{ (...items: ConcatArray<import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement>[]): import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement[]; (...items: (import("...' is not assignable to type '{ (...items: ConcatArray<import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement>[]): import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").J...'.
                      Types of parameters 'items' and 'items' are incompatible.
                        Type 'ConcatArray<import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement>' is not assignable to type 'ConcatArray<import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement>'.
                          Type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement' is not assignable to type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").JsonObjectExpressionStatement'.
                            Types of property 'expression' are incompatible.
                              Type 'ObjectLiteralExpression | ArrayLiteralExpression | JsonMinusNumericLiteral | NumericLiteral | StringLiteral | BooleanLiteral | NullLiteral' is not assignable to type 'JsonObjectExpression'.
                                Type 'ObjectLiteralExpression' is not assignable to type 'JsonObjectExpression'.
                                  Type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").ObjectLiteralExpression' is not assignable to type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").ObjectLiteralExpression'.
                                    Types of property 'kind' are incompatible.
                                      Type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/dtsgenerator/node_modules/typescript/lib/typescript").SyntaxKind.ObjectLiteralExpression' is not assignable to type 'import("/home/henke/github/dtsgenerator-create-operation-map/node_modules/typescript/lib/typescript").SyntaxKind.ObjectLiteralExpression'.

124                 const result = ts.transform(input, [factory]);
                                                        ~~~~~~~

    at createTSError (/home/henke/github/dtsgenerator-create-operation-map/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/henke/github/dtsgenerator-create-operation-map/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/henke/github/dtsgenerator-create-operation-map/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/henke/github/dtsgenerator-create-operation-map/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/henke/github/dtsgenerator-create-operation-map/node_modules/ts-node/src/index.ts:1043:43)
    at module.exports (/home/henke/github/dtsgenerator-create-operation-map/node_modules/default-require-extensions/js.js:7:9)
    at /home/henke/github/dtsgenerator-create-operation-map/node_modules/append-transform/index.js:64:4
    at require.extensions.<computed> (/home/henke/github/dtsgenerator-create-operation-map/node_modules/ts-node/src/index.ts:1046:12)
    at Object.<anonymous> (/home/henke/github/dtsgenerator-create-operation-map/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.exports.requireOrImport (/home/henke/github/dtsgenerator-create-operation-map/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/home/henke/github/dtsgenerator-create-operation-map/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/home/henke/github/dtsgenerator-create-operation-map/node_modules/mocha/lib/mocha.js:427:19)
    at singleRun (/home/henke/github/dtsgenerator-create-operation-map/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/home/henke/github/dtsgenerator-create-operation-map/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/home/henke/github/dtsgenerator-create-operation-map/node_modules/mocha/lib/cli/run.js:366:11)
    at /home/henke/github/dtsgenerator-create-operation-map/node_modules/yargs/lib/command.js:241:49
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtsgenerator-create-operation-map@0.1.0 do-test: `cross-env TS_NODE_FILES=true mocha --exit --require ts-node/register --colors test/*_test.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dtsgenerator-create-operation-map@0.1.0 do-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/henke/.npm/_logs/2020-09-15T07_10_30_592Z-debug.log
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

**Comment by horiuchi** [comment]
Sorry, please use the latest version.
